services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:rw
    networks:
      - medease-network
  # queue-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   command: php artisan queue:work
  #   environment:
  #     IS_WORKER: "true"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - storage:/usr/share/nginx/html/storage:rw
  #     - public:/usr/share/nginx/html/public:rw
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:ro
    networks:
      - medease-network
  db:
    image: mysql:8.2
    container_name: medease-db
    env_file:
      -  .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - medease-network
  # redis:
  #   image: bitnami/redis:7.2
  #   platform: linux/amd64
  #   ports:
  #     - 6379:6379
  #   restart: always
  #   volumes:
  #     - redis-data:/bitnami/redis/data
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   networks:
  #     - medease-network

networks:
  medease-network:
    driver: bridge

volumes:
  storage:
  public:
  db-data:
  redis-data:
